nombre = input("Introduce el nombre del personaje: ")
nivel = int(input("Introduce el nivel del personaje: "))
vida = float(input("Introduce la vida del personaje: "))
esta_vivo = bool(input("Introduce si el personaje está vivo (True/False): "))
VIDA_MAXIMA = 100.0 
print("Nombre del personaje:", nombre)
print("Nivel del personaje:", nivel)
print("Vida del personaje:", vida)
print("El personaje está vivo:", esta_vivo) 
print("Vida máxima del personaje:", VIDA_MAXIMA)